server:
  port: 8080
spring:
  devtools:
    restart:
      poll-interval: 1000ms #轮询间隔
      quiet-period: 999ms #静默
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://www.lixiaodong.club:3306/lingyi2?characterEncoding=utf-8
logging:
  level:
    com.lingyi: info
#path: "D:/test/test.log"
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.lingyi.domain
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  type-aliases-package: com.lingyi.bean
  check-config-location: false
  configuration:
    auto-mapping-behavior: partial
  global-config:
    db-config:
      db-type: mysql
      id-type: auto